[build]
  functions = "netlify/functions"
  command   = "npm run build"
  publish   = "dist"

[dev]
  command = "yarn dev:jobflow"  # Or "yarn dev:remorecap" to test the old app; switch as needed
  port = 9999
  targetPort = 5173