[build]
  command = "yarn build:all"
  publish = "apps/jobflow/dist"

[dev]
  command = "yarn dev:jobflow"
  port = 9999
  targetPort = 5173

[[redirects]]
  from = "/remorecap/*"
  to = "/apps/remorecap/dist/:splat"
  status = 200

[[redirects]]
  from = "/jobflow/*"
  to = "/apps/jobflow/dist/:splat"
  status = 200