[build]
  command = "yarn build:all"
  publish = "."  # Publish from root to include all sub-dists

[dev]
  command = "yarn dev:jobflow"
  port = 9999
  targetPort = 5173

[[redirects]]
  from = "/remorecap/*"
  to = "/dist/remorecap/:splat"
  status = 200

[[redirects]]
  from = "/jobflow/*"
  to = "/dist/jobflow/:splat"
  status = 200

# Catch-all for SPA client routing
[[redirects]]
  from = "/remorecap/*"
  to = "/dist/remorecap/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/jobflow/*"
  to = "/dist/jobflow/index.html"
  status = 200
  force = false

# Redirect root to jobflow
[[redirects]]
  from = "/"
  to = "/jobflow/"
  status = 301